/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TUGASUASPBO;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ANDINI
 */
public class frmBarang extends javax.swing.JFrame {

	Connection Con;
	ResultSet RsBrg;
	Statement stm;
	Boolean ada = false;
	String sSatuan;
	Boolean edit = false;
	private Object[][] dataTable = null;
	private String[] header = { "Kode", "Nama", "Satuan", "Harga Jual", "Biaya Pengadaan", "Stok", "Stok Min" };

	public frmBarang() {
		initComponents();
		open_db();
		baca_data();
		aktif(false);
		setTombol(true);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtStok = new javax.swing.JTextField();
        txtHargaBeli = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtStokMin = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbSatuan = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBrg = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmdTambah = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cmdSimpan = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cmdKoreksi = new javax.swing.JButton();
        txtKode = new javax.swing.JTextField();
        cmdHapus = new javax.swing.JButton();
        txtNama = new javax.swing.JTextField();
        cmdBatal = new javax.swing.JButton();
        txtHargaJual = new javax.swing.JTextField();
        cmdKeluar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(215, 218, 61));

        txtStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStokActionPerformed(evt);
            }
        });

        txtHargaBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaBeliActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Gurindam Tebal", 0, 18)); // NOI18N
        jLabel1.setText("Kode produk");

        txtStokMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStokMinActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Gurindam Tebal", 0, 18)); // NOI18N
        jLabel8.setText("biaya pengadaan");

        jLabel2.setFont(new java.awt.Font("Gurindam Tebal", 1, 36)); // NOI18N
        jLabel2.setText("Data Barang");

        cmbSatuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buah", "Kg" }));
        cmbSatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSatuanActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Gurindam Tebal", 0, 18)); // NOI18N
        jLabel3.setText("Nama buah");

        tblBrg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 223, 249), 3));
        tblBrg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode", "Nama", "Satuan", "Harga Jual", "Biaya Pengadaan", "Stok", "Stok Min"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblBrg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tblBrg);

        jLabel4.setFont(new java.awt.Font("Gurindam Tebal", 0, 18)); // NOI18N
        jLabel4.setText("Satuan");

        jLabel5.setFont(new java.awt.Font("Gurindam Tebal", 0, 18)); // NOI18N
        jLabel5.setText("harga jual");

        cmdTambah.setBackground(new java.awt.Color(0, 0, 0));
        cmdTambah.setFont(new java.awt.Font("Gurindam Tebal", 0, 14)); // NOI18N
        cmdTambah.setForeground(new java.awt.Color(255, 255, 255));
        cmdTambah.setText("Tambah");
        cmdTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTambahActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Gurindam Tebal", 0, 18)); // NOI18N
        jLabel6.setText("Stok");

        cmdSimpan.setBackground(new java.awt.Color(0, 0, 0));
        cmdSimpan.setFont(new java.awt.Font("Gurindam Tebal", 0, 14)); // NOI18N
        cmdSimpan.setForeground(new java.awt.Color(255, 255, 255));
        cmdSimpan.setText("Simpan");
        cmdSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSimpanActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Gurindam Tebal", 0, 18)); // NOI18N
        jLabel7.setText("Stok Minimal");

        cmdKoreksi.setBackground(new java.awt.Color(0, 0, 0));
        cmdKoreksi.setFont(new java.awt.Font("Gurindam Tebal", 0, 14)); // NOI18N
        cmdKoreksi.setForeground(new java.awt.Color(255, 255, 255));
        cmdKoreksi.setText("Koreksi");
        cmdKoreksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdKoreksiActionPerformed(evt);
            }
        });

        txtKode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodeActionPerformed(evt);
            }
        });

        cmdHapus.setBackground(new java.awt.Color(0, 0, 0));
        cmdHapus.setFont(new java.awt.Font("Gurindam Tebal", 0, 14)); // NOI18N
        cmdHapus.setForeground(new java.awt.Color(255, 255, 255));
        cmdHapus.setText("Hapus");
        cmdHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdHapusActionPerformed(evt);
            }
        });

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        cmdBatal.setBackground(new java.awt.Color(0, 0, 0));
        cmdBatal.setFont(new java.awt.Font("Gurindam Tebal", 0, 14)); // NOI18N
        cmdBatal.setForeground(new java.awt.Color(255, 255, 255));
        cmdBatal.setText("Batal");
        cmdBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBatalActionPerformed(evt);
            }
        });

        txtHargaJual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaJualActionPerformed(evt);
            }
        });

        cmdKeluar.setBackground(new java.awt.Color(0, 0, 0));
        cmdKeluar.setFont(new java.awt.Font("Gurindam Tebal", 0, 14)); // NOI18N
        cmdKeluar.setForeground(new java.awt.Color(255, 255, 255));
        cmdKeluar.setText("Keluar");
        cmdKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdKeluarActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel9.setBackground(new java.awt.Color(0, 91, 55));
        jLabel9.setFont(new java.awt.Font("Gurindam Tebal", 1, 60)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 91, 55));
        jLabel9.setText("taNBU");

        jLabel10.setFont(new java.awt.Font("Gurindam Tebal", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 91, 55));
        jLabel10.setText("(tandur buah)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(310, 310, 310))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(178, 178, 178))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(cmdTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdKoreksi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdBatal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdKeluar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel8)
                                                    .addGap(1, 1, 1)))
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtHargaBeli)
                                                .addComponent(txtKode)
                                                .addComponent(txtStokMin)
                                                .addComponent(txtHargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtNama)
                                                .addComponent(cmbSatuan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGap(33, 33, 33))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(265, 265, 265)
                                .addComponent(jLabel9)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cmbSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtHargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtHargaBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtStokMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdTambah)
                    .addComponent(cmdSimpan)
                    .addComponent(cmdKoreksi)
                    .addComponent(cmdHapus)
                    .addComponent(cmdBatal)
                    .addComponent(cmdKeluar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void cmdHapusActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cmdHapusActionPerformed
		try {
			String sql = "delete from barang where kd_brg='" + txtKode.getText() + "'";
			stm.executeUpdate(sql);
			baca_data();

			edit = false; // set ulang edit agar form tidak masuk ke mode edit
		} catch (SQLException e) {
			JOptionPane.showMessageDialog(null, e);
		}
		// TODO add your handling code here:
	}// GEN-LAST:event_cmdHapusActionPerformed

	private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtNamaActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtNamaActionPerformed

	private void cmdBatalActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cmdBatalActionPerformed
		aktif(false);
		setTombol(true);
		// TODO add your handling code here:
	}// GEN-LAST:event_cmdBatalActionPerformed

	private void txtHargaJualActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtHargaJualActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtHargaJualActionPerformed

	private void cmdKeluarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cmdKeluarActionPerformed
		dispose();
		// TODO add your handling code here:
	}// GEN-LAST:event_cmdKeluarActionPerformed

	private void txtStokActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtStokActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtStokActionPerformed

	private void txtHargaBeliActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtHargaBeliActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtHargaBeliActionPerformed

	private void txtStokMinActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtStokMinActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtStokMinActionPerformed

	private void cmbSatuanActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cmbSatuanActionPerformed                                         
            JComboBox cSatuan = (javax.swing.JComboBox)evt.getSource();
            //Membaca Item Yang Terpilih — > String
            sSatuan = (String)cSatuan.getSelectedItem();	
// TODO add your handling code here:
	}// GEN-LAST:event_cmbSatuanActionPerformed

	private void cmdTambahActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cmdTambahActionPerformed
		aktif(true);
		setTombol(false);
		kosong();
		// TODO add your handling code here:
	}// GEN-LAST:event_cmdTambahActionPerformed

	private void cmdSimpanActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cmdSimpanActionPerformed
		String tKode = txtKode.getText();
		String tNama = txtNama.getText();
		double hrg_jual = Double.parseDouble(txtHargaJual.getText());
		double hrg_beli = Double.parseDouble(txtHargaBeli.getText());
		int stk = Integer.parseInt(txtStok.getText());
		int stkMin = Integer.parseInt(txtStokMin.getText());

		try {
			if (edit == true) {
				stm.executeUpdate("update barang set nm_brg='" + tNama + "',satuan='" + sSatuan + "'," + "harga_jual="
						+ hrg_jual + "'," + "biaya_pengadaan=" + hrg_beli + ",stok=" + stk + ",stok_min=" + stkMin
						+ " where kd_brg='" + tKode + "'");
			} else {
				stm.executeUpdate("INSERT into barang(kd_brg, nm_brg, satuan, harga_jual, biaya_pengadaan, stok, stok_min) "
						+ "VALUES('" + tKode + "','" + tNama + "','" + sSatuan + "'," + hrg_jual + "," + hrg_beli + ","
						+ stk + "," + stkMin + ")");
			}

			tblBrg.setModel(new DefaultTableModel(dataTable, header));
			baca_data();
			aktif(false);
			setTombol(true);
		} catch (SQLException e) {
			JOptionPane.showMessageDialog(null, e);
		}
		// TODO add your handling code here:
	}// GEN-LAST:event_cmdSimpanActionPerformed

	private void cmdKoreksiActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cmdKoreksiActionPerformed
		edit = true;
		aktif(true);
		setTombol(false);
		txtKode.setEditable(false);
		// TODO add your handling code here:
	}// GEN-LAST:event_cmdKoreksiActionPerformed

	private void txtKodeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtKodeActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtKodeActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(frmBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(frmBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(frmBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(frmBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new frmBarang().setVisible(true);
			}
		});
	}

	// method untuk memindahkan data dr table ke form
	private void setField() {
		int row = tblBrg.getSelectedRow();
		txtKode.setText((String) tblBrg.getValueAt(row, 0));
		txtNama.setText((String) tblBrg.getValueAt(row, 1));
		cmbSatuan.setSelectedItem((String) tblBrg.getValueAt(row, 2));
		String harga_jual = Double.toString((Double) tblBrg.getValueAt(row, 3));
		txtHargaJual.setText(harga_jual);
		String biaya_pengadaan = Double.toString((Double) tblBrg.getValueAt(row, 4));
		txtHargaBeli.setText(biaya_pengadaan);
		String stok = Integer.toString((Integer) tblBrg.getValueAt(row, 5));
		txtStok.setText(stok);
		String stokmin = Integer.toString((Integer) tblBrg.getValueAt(row, 6));
		txtStokMin.setText(stokmin);
	}

	// method membuka database server, user, pass, database disesuaikan
	private void open_db() {
		try {
			KoneksiMysql kon = new KoneksiMysql("localhost", "root", "", "tugasakhirpbo");
			Con = kon.getConnection();
			// System.out.println("Berhasil ");
		} catch (Exception e) {
			System.out.println("Error : " + e);
		}
	}

	// method baca data dari Mysql dimasukkan ke table pada form
	private void baca_data() {
		try {
			stm = Con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
			// stm = Con.createStatement();
			RsBrg = stm.executeQuery("select * from barang");
			ResultSetMetaData meta = RsBrg.getMetaData();
			int col = meta.getColumnCount();
			int baris = 0;
			while (RsBrg.next()) {
				baris = RsBrg.getRow();
			}

			dataTable = new Object[baris][col];
			int x = 0;
			RsBrg.beforeFirst();

			while (RsBrg.next()) {
				dataTable[x][0] = RsBrg.getString("kd_brg");
				dataTable[x][1] = RsBrg.getString("nm_brg");
				dataTable[x][2] = RsBrg.getString("satuan");
				dataTable[x][3] = RsBrg.getDouble("harga_jual");
				dataTable[x][4] = RsBrg.getDouble("biaya_pengadaan");
				dataTable[x][5] = RsBrg.getInt("stok");
				dataTable[x][6] = RsBrg.getInt("stok_min");
				x++;
			}

			tblBrg.setModel(new DefaultTableModel(dataTable, header));
			// DefaultTableModel model = (DefaultTableModel) tblBrg.getModel();
			// model.setDataVector(dataTable, header);
		} catch (SQLException e) {
			JOptionPane.showMessageDialog(null, e);
		}
	}

	// untuk mengkosongkan isian data
	private void kosong() {
		txtKode.setText("");
		txtNama.setText("");
		cmbSatuan.setSelectedIndex(0);
		txtHargaJual.setText("");
		txtHargaBeli.setText("");
		txtStok.setText("");
		txtStokMin.setText("");
	}

	// mengset aktif tidak isian data
	private void aktif(boolean x) {
		txtKode.setEditable(x);
		txtNama.setEditable(x);
		cmbSatuan.setEnabled(x);
		txtHargaJual.setEditable(x);
		txtHargaBeli.setEditable(x);
		txtStok.setEditable(x);
		txtStokMin.setEditable(x);
	}

	// mengset tombol on/off
	private void setTombol(boolean t) {
		cmdTambah.setEnabled(t);
		cmdKoreksi.setEnabled(t);
		cmdHapus.setEnabled(t);
		cmdSimpan.setEnabled(!t);
		cmdBatal.setEnabled(!t);
		cmdKeluar.setEnabled(t);
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbSatuan;
    private javax.swing.JButton cmdBatal;
    private javax.swing.JButton cmdHapus;
    private javax.swing.JButton cmdKeluar;
    private javax.swing.JButton cmdKoreksi;
    private javax.swing.JButton cmdSimpan;
    private javax.swing.JButton cmdTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblBrg;
    private javax.swing.JTextField txtHargaBeli;
    private javax.swing.JTextField txtHargaJual;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtStok;
    private javax.swing.JTextField txtStokMin;
    // End of variables declaration//GEN-END:variables
}
