/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TUGASUASPBO;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ANDINI
 */
public class frmKonsumen extends javax.swing.JFrame {

	Connection Con;
	ResultSet RsBrg;
	Statement stm;
	Boolean ada = false;
	String sSatuan;
	Boolean edit = false;
	private Object[][] dataTable = null;
	private String[] header = { "Kode", "Nama Konsumen", "Alamat", "Kota", "Kode Pos", "Phone", "Email" };

	public frmKonsumen() {
		initComponents();
		open_db();
		baca_data();
		aktif(false);
		setTombol(true);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmdKoreksi = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        cmdTambah = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmdKeluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBrg = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtKodePos = new javax.swing.JTextField();
        cmdSimpan = new javax.swing.JButton();
        txtEmail = new javax.swing.JTextField();
        cmdHapus = new javax.swing.JButton();
        txtAlamat = new javax.swing.JTextField();
        cmdBatal = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        txtKota = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTelepon = new javax.swing.JTextField();
        txtKodeKonsumen = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(215, 218, 61));

        cmdKoreksi.setBackground(new java.awt.Color(0, 0, 0));
        cmdKoreksi.setFont(new java.awt.Font("Gurindam Tebal", 1, 10)); // NOI18N
        cmdKoreksi.setForeground(new java.awt.Color(255, 255, 255));
        cmdKoreksi.setText("Koreksi");
        cmdKoreksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdKoreksiActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Gurindam Tebal", 0, 18)); // NOI18N
        jLabel8.setText("Kode Pos");

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        cmdTambah.setBackground(new java.awt.Color(0, 0, 0));
        cmdTambah.setFont(new java.awt.Font("Gurindam Tebal", 1, 10)); // NOI18N
        cmdTambah.setForeground(new java.awt.Color(255, 255, 255));
        cmdTambah.setText("Tambah");
        cmdTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTambahActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Gurindam Tebal", 1, 36)); // NOI18N
        jLabel2.setText("Data Konsumen");

        cmdKeluar.setBackground(new java.awt.Color(0, 0, 0));
        cmdKeluar.setFont(new java.awt.Font("Gurindam Tebal", 1, 10)); // NOI18N
        cmdKeluar.setForeground(new java.awt.Color(255, 255, 255));
        cmdKeluar.setText("Keluar");
        cmdKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdKeluarActionPerformed(evt);
            }
        });

        tblBrg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 223, 249), 3));
        tblBrg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode", "Nama Konsumen", "Alamat", "Kota", "Kode Pos", "Phone", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblBrg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tblBrg);

        jLabel3.setFont(new java.awt.Font("Gurindam Tebal", 0, 18)); // NOI18N
        jLabel3.setText("Nama Konsumen");

        jLabel5.setFont(new java.awt.Font("Gurindam Tebal", 0, 18)); // NOI18N
        jLabel5.setText("Kota");

        jLabel7.setFont(new java.awt.Font("Gurindam Tebal", 0, 18)); // NOI18N
        jLabel7.setText("Email");

        txtKodePos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodePosActionPerformed(evt);
            }
        });

        cmdSimpan.setBackground(new java.awt.Color(0, 0, 0));
        cmdSimpan.setFont(new java.awt.Font("Gurindam Tebal", 1, 10)); // NOI18N
        cmdSimpan.setForeground(new java.awt.Color(255, 255, 255));
        cmdSimpan.setText("Simpan");
        cmdSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSimpanActionPerformed(evt);
            }
        });

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        cmdHapus.setBackground(new java.awt.Color(0, 0, 0));
        cmdHapus.setFont(new java.awt.Font("Gurindam Tebal", 1, 10)); // NOI18N
        cmdHapus.setForeground(new java.awt.Color(255, 255, 255));
        cmdHapus.setText("Hapus");
        cmdHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdHapusActionPerformed(evt);
            }
        });

        txtAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlamatActionPerformed(evt);
            }
        });

        cmdBatal.setBackground(new java.awt.Color(0, 0, 0));
        cmdBatal.setFont(new java.awt.Font("Gurindam Tebal", 1, 10)); // NOI18N
        cmdBatal.setForeground(new java.awt.Color(255, 255, 255));
        cmdBatal.setText("Batal");
        cmdBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBatalActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        txtKota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKotaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Gurindam Tebal", 0, 18)); // NOI18N
        jLabel1.setText("Kode Konsumen");

        jLabel4.setFont(new java.awt.Font("Gurindam Tebal", 0, 18)); // NOI18N
        jLabel4.setText("Alamat");

        txtTelepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeleponActionPerformed(evt);
            }
        });

        txtKodeKonsumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodeKonsumenActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Gurindam Tebal", 0, 18)); // NOI18N
        jLabel6.setText("Telepon");

        jLabel9.setBackground(new java.awt.Color(0, 91, 55));
        jLabel9.setFont(new java.awt.Font("Gurindam Tebal", 1, 60)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 91, 55));
        jLabel9.setText("taNBU");

        jLabel10.setFont(new java.awt.Font("Gurindam Tebal", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 91, 55));
        jLabel10.setText("(tandur buah)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel1))
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtKodeKonsumen)
                                            .addComponent(txtNama)
                                            .addComponent(txtAlamat)
                                            .addComponent(txtKota)
                                            .addComponent(txtKodePos)
                                            .addComponent(txtTelepon)
                                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(cmdTambah)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cmdSimpan)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cmdKoreksi)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cmdHapus)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cmdBatal)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cmdKeluar))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKodeKonsumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtKota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtKodePos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdTambah)
                    .addComponent(cmdSimpan)
                    .addComponent(cmdKoreksi)
                    .addComponent(cmdHapus)
                    .addComponent(cmdBatal)
                    .addComponent(cmdKeluar))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void cmdHapusActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cmdHapusActionPerformed
		try {
			String sql = "delete from konsumen where kd_kons='" + txtKodeKonsumen.getText() + "'";
			stm.executeUpdate(sql);
			baca_data();

			edit = false; // set ulang edit agar form tidak masuk ke mode edit
		} catch (SQLException e) {
			JOptionPane.showMessageDialog(null, e);
		}
		// TODO add your handling code here:
	}// GEN-LAST:event_cmdHapusActionPerformed

	private void txtAlamatActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtAlamatActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtAlamatActionPerformed

	private void cmdBatalActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cmdBatalActionPerformed

		// TODO add your handling code here:
	}// GEN-LAST:event_cmdBatalActionPerformed

	private void txtKotaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtKotaActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtKotaActionPerformed

	private void txtTeleponActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtTeleponActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtTeleponActionPerformed

	private void cmdKeluarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cmdKeluarActionPerformed
		dispose();
		// TODO add your handling code here:
	}// GEN-LAST:event_cmdKeluarActionPerformed

	private void txtKodePosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtKodePosActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtKodePosActionPerformed

	private void cmdSimpanActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cmdSimpanActionPerformed
		String tKodeKons = txtKodeKonsumen.getText();
		String tNama = txtNama.getText();
		String tAlamat = txtAlamat.getText();
		String tKota = txtKota.getText();
		String tKodePos = txtKodePos.getText();
		String tTelepon = txtTelepon.getText();
		String tEmail = txtEmail.getText();

		try {
			if (edit == true) {
				stm.executeUpdate("update konsumen set nm_kons='"+tNama+"',"+ "alm='"+tAlamat+"',kota='"+tKota+"',kd_pos='"+tKodePos+"',phone='"+tTelepon+"',email='"+tEmail+"' where kd_kons='" + tKodeKons + "'");
			} else {
				stm.executeUpdate("INSERT into konsumen(kd_kons, nm_kons, alm, kota, kd_pos, phone, email) " + "VALUES('" + tKodeKons + "','" + tNama + "','" + tAlamat + "','" + tKota + "','" + tKodePos + "','" + tTelepon + "','" + tEmail + "')");
			}

			tblBrg.setModel(new DefaultTableModel(dataTable, header));
			baca_data();
			aktif(false);
			setTombol(true);
		} catch (SQLException e) {
			JOptionPane.showMessageDialog(null, e);
		}
		// TODO add your handling code here:
	}// GEN-LAST:event_cmdSimpanActionPerformed

	private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtEmailActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtEmailActionPerformed

	private void txtKodeKonsumenActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtKodeKonsumenActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtKodeKonsumenActionPerformed

	private void cmdKoreksiActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cmdKoreksiActionPerformed
		edit = true;
		aktif(true);
		setTombol(false);
		txtKodeKonsumen.setEditable(false);
		// TODO add your handling code here:
	}// GEN-LAST:event_cmdKoreksiActionPerformed

	private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtNamaActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtNamaActionPerformed

	private void cmdTambahActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cmdTambahActionPerformed
		aktif(true);
		setTombol(false);
		kosong();
		// TODO add your handling code here:
	}// GEN-LAST:event_cmdTambahActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(frmKonsumen.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(frmKonsumen.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(frmKonsumen.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(frmKonsumen.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new frmKonsumen().setVisible(true);
			}
		});
	}

	// method untuk memindahkan data dr table ke form
	private void setField() {
		int row = tblBrg.getSelectedRow();
		txtKodeKonsumen.setText((String) tblBrg.getValueAt(row, 0));
		txtNama.setText((String) tblBrg.getValueAt(row, 1));
		txtAlamat.setText((String) tblBrg.getValueAt(row, 2));
		txtKota.setText((String) tblBrg.getValueAt(row, 3));
		txtKodePos.setText((String) tblBrg.getValueAt(row, 4));
		txtTelepon.setText((String) tblBrg.getValueAt(row, 5));
		txtEmail.setText((String) tblBrg.getValueAt(row, 6));
	}

	// method membuka database server, user, pass, database disesuaikan
	private void open_db() {
		try {
			KoneksiMysql kon = new KoneksiMysql("localhost", "root", "", "tugasakhirpbo");
			Con = kon.getConnection();
			// System.out.println("Berhasil ");
		} catch (Exception e) {
			System.out.println("Error : " + e);
		}
	}

	// method baca data dari Mysql dimasukkan ke table pada form
	private void baca_data() {
		try {
			stm = Con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
			// stm = Con.createStatement();
			RsBrg = stm.executeQuery("select * from konsumen");
			ResultSetMetaData meta = RsBrg.getMetaData();
			int col = meta.getColumnCount();
			int baris = 0;
			while (RsBrg.next()) {
				baris = RsBrg.getRow();
			}

			dataTable = new Object[baris][col];
			int x = 0;
			RsBrg.beforeFirst();

			while (RsBrg.next()) {
				dataTable[x][0] = RsBrg.getString("kd_kons");
				dataTable[x][1] = RsBrg.getString("nm_kons");
				dataTable[x][2] = RsBrg.getString("alm");
				dataTable[x][3] = RsBrg.getString("kota");
				dataTable[x][4] = RsBrg.getString("kd_pos");
				dataTable[x][5] = RsBrg.getString("phone");
				dataTable[x][6] = RsBrg.getString("email");
				x++;
			}

			tblBrg.setModel(new DefaultTableModel(dataTable, header));
			// DefaultTableModel model = (DefaultTableModel) tblBrg.getModel();
			// model.setDataVector(dataTable, header);
		} catch (SQLException e) {
			JOptionPane.showMessageDialog(null, e);
		}
	}

	// untuk mengkosongkan isian data
	private void kosong() {
		txtKodeKonsumen.setText("");
		txtNama.setText("");
		txtAlamat.setText("");
		txtKota.setText("");
		txtKodePos.setText("");
		txtTelepon.setText("");
		txtEmail.setText("");
	}

	// mengset aktif tidak isian data
	private void aktif(boolean x) {
		txtKodeKonsumen.setEditable(x);
		txtNama.setEditable(x);
		txtAlamat.setEditable(x);
		txtKota.setEditable(x);
		txtKodePos.setEditable(x);
		txtTelepon.setEditable(x);
		txtEmail.setEditable(x);
	}

	// mengset tombol on/off
	private void setTombol(boolean t) {
		cmdTambah.setEnabled(t);
		cmdKoreksi.setEnabled(t);
		cmdHapus.setEnabled(t);
		cmdSimpan.setEnabled(!t);
		cmdBatal.setEnabled(!t);
		cmdKeluar.setEnabled(t);
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBatal;
    private javax.swing.JButton cmdHapus;
    private javax.swing.JButton cmdKeluar;
    private javax.swing.JButton cmdKoreksi;
    private javax.swing.JButton cmdSimpan;
    private javax.swing.JButton cmdTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblBrg;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtKodeKonsumen;
    private javax.swing.JTextField txtKodePos;
    private javax.swing.JTextField txtKota;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTelepon;
    // End of variables declaration//GEN-END:variables
}
