/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TUGASUASPBO;

import java.awt.print.PrinterException;
import java.sql.*;
import java.text.MessageFormat;
import java.util.Calendar;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ANDINI
 */
public class frmTransaksi extends javax.swing.JFrame {

	Connection Con;
	ResultSet RsBrg;
	ResultSet RsKons;
	Statement stm;
	double total = 0;
	String tanggal;
	Boolean edit = false;
	DefaultTableModel tableModel = new DefaultTableModel(new Object[][] {},
			new String[] { "Kd Barang", "Nama Barang", "Harga Barang", "Jumlah", "Total" });
	// Var Pencarian Kode Barang
	String idBrg;
	String namaBrg;
	String hargaBrg;

	public frmTransaksi() {
		initComponents();
		open_db();
		inisialisasi_tabel();
		aktif(false);
		setTombol(true);
		txtTgl.setEditor(new JSpinner.DateEditor(txtTgl, "yyyy/MM/dd"));
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmdCetak = new javax.swing.JButton();
        txtNama = new javax.swing.JTextField();
        txtNm_Brg = new javax.swing.JTextField();
        btnPilih = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBayar = new javax.swing.JTextField();
        txtNoJual = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtKembali = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbKd_Brg = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextArea();
        txtHarga = new javax.swing.JTextField();
        txtJml = new javax.swing.JTextField();
        cmbKd_Kons = new javax.swing.JComboBox<>();
        txtTot = new javax.swing.JTextField();
        cmdHapusItem = new javax.swing.JButton();
        txtTgl = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblJual = new javax.swing.JTable();
        cmdKeluar = new javax.swing.JButton();
        cmdTambah = new javax.swing.JButton();
        cmdSimpan = new javax.swing.JButton();
        cmdBatal = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(215, 218, 61));

        cmdCetak.setBackground(new java.awt.Color(0, 0, 0));
        cmdCetak.setFont(new java.awt.Font("Gurindam Tebal", 0, 14)); // NOI18N
        cmdCetak.setForeground(new java.awt.Color(255, 255, 255));
        cmdCetak.setText("Cetak");
        cmdCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCetakActionPerformed(evt);
            }
        });

        txtNm_Brg.setPreferredSize(new java.awt.Dimension(110, 22));

        btnPilih.setText("Pilih Barang");
        btnPilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihActionPerformed(evt);
            }
        });

        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel1.setText("No Jual");

        jLabel5.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel5.setText("TOTAL");

        jLabel2.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel2.setText("Tgl. Jual");

        txtBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBayarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel6.setText("BAYAR");

        jLabel3.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel3.setText("Kode Konsumen");

        jLabel4.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel4.setText("Nama Konsumen");

        jLabel7.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel7.setText("KEMBALI");

        cmbKd_Brg.setModel(cmbKd_Brg.getModel());
        cmbKd_Brg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbKd_BrgActionPerformed(evt);
            }
        });

        text.setColumns(20);
        text.setRows(5);
        jScrollPane2.setViewportView(text);

        txtHarga.setPreferredSize(new java.awt.Dimension(110, 22));

        txtJml.setPreferredSize(new java.awt.Dimension(110, 22));
        txtJml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJmlActionPerformed(evt);
            }
        });

        cmbKd_Kons.setModel(cmbKd_Kons.getModel());
        cmbKd_Kons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbKd_KonsActionPerformed(evt);
            }
        });

        txtTot.setPreferredSize(new java.awt.Dimension(110, 22));
        txtTot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotActionPerformed(evt);
            }
        });

        cmdHapusItem.setText("Hapus Item");
        cmdHapusItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdHapusItemActionPerformed(evt);
            }
        });

        txtTgl.setModel(new javax.swing.SpinnerDateModel());

        tblJual.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 223, 249), 3));
        tblJual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kd Barang", "Nama Barang", "Harga Barang", "Jumlah", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblJual.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tblJual);

        cmdKeluar.setBackground(new java.awt.Color(0, 0, 0));
        cmdKeluar.setFont(new java.awt.Font("Gurindam Tebal", 0, 14)); // NOI18N
        cmdKeluar.setForeground(new java.awt.Color(255, 255, 255));
        cmdKeluar.setText("Keluar");
        cmdKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdKeluarActionPerformed(evt);
            }
        });

        cmdTambah.setBackground(new java.awt.Color(0, 0, 0));
        cmdTambah.setFont(new java.awt.Font("Gurindam Tebal", 0, 14)); // NOI18N
        cmdTambah.setForeground(new java.awt.Color(255, 255, 255));
        cmdTambah.setText("Tambah");
        cmdTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTambahActionPerformed(evt);
            }
        });

        cmdSimpan.setBackground(new java.awt.Color(0, 0, 0));
        cmdSimpan.setFont(new java.awt.Font("Gurindam Tebal", 0, 14)); // NOI18N
        cmdSimpan.setForeground(new java.awt.Color(255, 255, 255));
        cmdSimpan.setText("Simpan");
        cmdSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSimpanActionPerformed(evt);
            }
        });

        cmdBatal.setBackground(new java.awt.Color(0, 0, 0));
        cmdBatal.setFont(new java.awt.Font("Gurindam Tebal", 0, 14)); // NOI18N
        cmdBatal.setForeground(new java.awt.Color(255, 255, 255));
        cmdBatal.setText("Batal");
        cmdBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBatalActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Gurindam Tebal", 1, 36)); // NOI18N
        jLabel8.setText("TRANSAKSI");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel10.setFont(new java.awt.Font("Gurindam Tebal", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 91, 55));
        jLabel10.setText("(tandur buah)");

        jLabel9.setBackground(new java.awt.Color(0, 91, 55));
        jLabel9.setFont(new java.awt.Font("Gurindam Tebal", 1, 60)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 91, 55));
        jLabel9.setText("taNBU");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cmdTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdSimpan)
                        .addGap(18, 18, 18)
                        .addComponent(cmdBatal)
                        .addGap(18, 18, 18)
                        .addComponent(cmdCetak)
                        .addGap(18, 18, 18)
                        .addComponent(cmdKeluar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtBayar)
                                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(21, 21, 21))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTgl, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNoJual, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNama)
                            .addComponent(cmbKd_Kons, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmdHapusItem)
                                .addGap(18, 18, 18)
                                .addComponent(btnPilih)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmbKd_Brg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtNm_Brg, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtJml, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTot, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(270, 270, 270))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(218, 218, 218)
                                .addComponent(jLabel10)
                                .addGap(289, 289, 289))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(239, 239, 239)
                                .addComponent(jLabel9)))
                        .addGap(31, 31, 31))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNoJual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 5, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cmbKd_Kons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbKd_Brg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNm_Brg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdHapusItem)
                    .addComponent(btnPilih)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdTambah)
                    .addComponent(cmdSimpan)
                    .addComponent(cmdBatal)
                    .addComponent(cmdKeluar)
                    .addComponent(cmdCetak))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void cmdKeluarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cmdKeluarActionPerformed
		dispose();
		// TODO add your handling code here:
	}// GEN-LAST:event_cmdKeluarActionPerformed

	private void cmdTambahActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cmdTambahActionPerformed
		aktif(true);
		setTombol(false);
		baca_barang();
		baca_konsumen();
		kosong();
		kosong_detail();
		kosong_table();
		nomor_jual();
		// TODO add your handling code here:
	}// GEN-LAST:event_cmdTambahActionPerformed

	private void cmdSimpanActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cmdSimpanActionPerformed
		simpan_transaksi();
		inisialisasi_tabel();
		// TODO add your handling code here:
	}// GEN-LAST:event_cmdSimpanActionPerformed

	private void cmdBatalActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cmdBatalActionPerformed
		aktif(false);
		setTombol(true);
		kosong();
		kosong_detail();
		kosong_table();
		text.setText("");
		// TODO add your handling code here:
	}// GEN-LAST:event_cmdBatalActionPerformed

	private void cmdCetakActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cmdCetakActionPerformed
		format_tanggal();
		String ctk = "Nota Penjualan\nNo:" + txtNoJual.getText() + "\nTanggal : " + tanggal;
		ctk = ctk + "\n"
				+ "--------------------------------------------------------------------------------------------------------------------------------";
		ctk = ctk + "\n" + "Kode\tNama Barang\t\tHarga\tJml\tTotal";
		ctk = ctk + "\n"
				+ "--------------------------------------------------------------------------------------------------------------------------------";

		for (int i = 0; i < tblJual.getRowCount(); i++) {
			String xkd = (String) tblJual.getValueAt(i, 0);
			String xnama = (String) tblJual.getValueAt(i, 1);
			double xhrg = (Double) tblJual.getValueAt(i, 2);
			int xjml = (Integer) tblJual.getValueAt(i, 3);
			double xtot = (Double) tblJual.getValueAt(i, 4);
			ctk = ctk + "\n" + xkd + "\t" + xnama + "\t\t" + xhrg + "\t" + xjml + "\t" + xtot;
		}

		ctk = ctk + "\n"
				+ "--------------------------------------------------------------------------------------------------------------------------------";
		ctk = ctk + "\n\t\t\t\t\t" + "Total : " + txtTotal.getText();
                ctk = ctk + "\n\t\t\t\t\t" + "Bayar : " + txtBayar.getText();
                ctk = ctk + "\n\t\t\t\t\t" + "Kembali : " + txtKembali.getText();
                ctk = ctk + "\n"
				+ "--------------------------------------------------------------------------------------------------------------------------------";
		text.setText(ctk);

		String headerField = "";
		String footerField = "";
		MessageFormat header = new MessageFormat(headerField);
		MessageFormat footer = new MessageFormat(footerField);
		boolean interactive = true;// interactiveCheck.isSelected();
		boolean background = true;// backgroundCheck.isSelected();
		PrintingTask task = new PrintingTask(header, footer, interactive);

		if (background) {
			task.execute();
		} else {
			task.run();
		}
		// TODO add your handling code here:
	}// GEN-LAST:event_cmdCetakActionPerformed

	private void cmbKd_BrgActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cmbKd_BrgActionPerformed
		String kdBrg = cmbKd_Brg.getSelectedItem().toString();
		detail_barang(kdBrg);
		// TODO add your handling code here:
	}// GEN-LAST:event_cmbKd_BrgActionPerformed

	private void cmdHapusItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cmdHapusItemActionPerformed
		try {
			int row = tblJual.getSelectedRow(); // Mendapatkan baris yang dipilih

			if (row != -1) { // Memastikan ada baris yang dipilih
				tableModel.removeRow(row); // Menghapus baris dari tableModel
				inisialisasi_tabel(); // Memperbarui tampilan tabel
			} else {
				JOptionPane.showMessageDialog(null, "Pilih baris yang ingin dihapus");
			}
		} catch (Exception e) {
			System.out.println("Error: " + e);
		}
		// TODO add your handling code here:
	}// GEN-LAST:event_cmdHapusItemActionPerformed

	private void btnPilihActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnPilihActionPerformed
		frmSelectBarang fDB = new frmSelectBarang();
		fDB.fAB = this;
		fDB.setVisible(true);
		fDB.setResizable(false);
		// TODO add your handling code here:
	}// GEN-LAST:event_btnPilihActionPerformed

	private void cmbKd_KonsActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cmbKd_KonsActionPerformed
		String kdKons = cmbKd_Kons.getSelectedItem().toString();
		detail_konsumen(kdKons);
		// TODO add your handling code here:
	}// GEN-LAST:event_cmbKd_KonsActionPerformed

	private void txtBayarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtBayarActionPerformed
		hitung_bayar();
		// TODO add your handling code here:
	}// GEN-LAST:event_txtBayarActionPerformed

	private void txtTotActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtTotActionPerformed

// TODO add your handling code here:
	}// GEN-LAST:event_txtTotActionPerformed

	private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtTotalActionPerformed

		// TODO add your handling code here:
	}// GEN-LAST:event_txtTotalActionPerformed

	private void txtJmlActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtJmlActionPerformed
		hitung_jual();
		simpan_ditabel();
		// TODO add your handling code here:
	}// GEN-LAST:event_txtJmlActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(frmTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(frmTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(frmTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(frmTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new frmTransaksi().setVisible(true);
			}
		});
	}

	// method membuka database server, user, pass, database disesuaikan
	private void open_db() {
		try {
			KoneksiMysql kon = new KoneksiMysql("localhost", "root", "", "tugasakhirpbo");
			Con = kon.getConnection();
			// System.out.println("Berhasil ");
		} catch (Exception e) {
			System.out.println("Error : " + e);
		}
	}

	// method hitung penjualan
	private void hitung_jual() {
		double xtot, xhrg;
		int xjml;

		xhrg = Double.parseDouble(txtHarga.getText());
		xjml = Integer.parseInt(txtJml.getText());
		xtot = xhrg * xjml;
		String xtotal = Double.toString(xtot);
		txtTot.setText(xtotal);
		total = total + xtot;
		txtTotal.setText(Double.toString(total));
	}

	// methohd baca data konsumen
	private void baca_konsumen() {
		DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();

		try {
			stm = Con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
			RsKons = stm.executeQuery("SELECT kd_kons FROM konsumen");

			while (RsKons.next()) {
				String kodeKonsumen = RsKons.getString("kd_kons");
				model.addElement(kodeKonsumen);
			}

			RsKons.close();
		} catch (SQLException e) {
			e.printStackTrace();
		}

		cmbKd_Kons.setModel(model);
	}

	private void baca_barang() {
		DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();

		try {
			stm = Con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
			RsBrg = stm.executeQuery("SELECT kd_brg FROM barang");

			while (RsBrg.next()) {
				String kodeBarang = RsBrg.getString("kd_brg");
				model.addElement(kodeBarang);
			}

			RsBrg.close();
		} catch (SQLException e) {
			e.printStackTrace();
		}

		cmbKd_Brg.setModel(model);
	}

	// method baca barang setelah combo barang di klik
	private void detail_barang(String xkode) {
		try {
			stm = Con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
			RsBrg = stm.executeQuery("select * from barang where kd_brg = '" + xkode + "'");

			if (RsBrg.next()) {
				String namaBrg = RsBrg.getString("nm_brg");
				int hargaBrg = RsBrg.getInt("harga_jual");

				txtNm_Brg.setText(namaBrg);
				txtHarga.setText(Integer.toString(hargaBrg));
			} else {
				txtNm_Brg.setText("");
				txtHarga.setText("");
			}

			RsBrg.close();
		} catch (SQLException e) {
			JOptionPane.showMessageDialog(null, e);
		}
	}

	// method baca konsumen setelah combo konsumen di klik
	private void detail_konsumen(String xkode) {
		try {
			stm = Con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
			RsKons = stm.executeQuery("select * from konsumen where kd_kons = '" + xkode + "'");

			if (RsKons.next()) {
				String namaKons = RsKons.getString("nm_kons");
				txtNama.setText(namaKons);
			} else {
				txtNama.setText("");
			}

		} catch (SQLException e) {
			JOptionPane.showMessageDialog(null, e);
		}
	}

	// method set model tabel
	public void inisialisasi_tabel() {
		tblJual.setModel(tableModel);
	}

	// method pengkosongan isian
	private void kosong() {
		txtNoJual.setText("");
		txtNm_Brg.setText("");
		txtHarga.setText("");
		txtTotal.setText("");
	}

	// method kosongkan detail jual
	private void kosong_detail() {
		txtNm_Brg.setText("");
		txtHarga.setText("");
		txtJml.setText("");
		txtTot.setText("");
	}

	// mengset aktif tidak isian data
	private void aktif(boolean x) {
		txtNoJual.setEnabled(x);
		txtNoJual.setEditable(false);

		txtNama.setEnabled(x);
		txtNama.setEditable(false);

		txtNm_Brg.setEnabled(x);
		txtNm_Brg.setEditable(false);

		txtHarga.setEnabled(x);
		txtHarga.setEditable(false);

		txtJml.setEnabled(x);
		txtTot.setEnabled(x);
		txtTot.setEditable(false);

		txtTotal.setEnabled(x);
		txtTotal.setEditable(false);

		txtBayar.setEnabled(x);

		txtKembali.setEnabled(x);
		txtKembali.setEditable(false);

		txtTot.setEnabled(x);
		txtTotal.setEnabled(x);
		txtId.setEnabled(x);

		cmbKd_Kons.setEnabled(x);
		cmbKd_Brg.setEnabled(x);
		txtTgl.setEnabled(x);
		txtJml.setEditable(x);
	}

	// method set tombol on/off
	private void setTombol(boolean t) {
		cmdTambah.setEnabled(t);
		cmdSimpan.setEnabled(!t);
		cmdBatal.setEnabled(!t);
		cmdKeluar.setEnabled(t);
		cmdHapusItem.setEnabled(!t);
		btnPilih.setEnabled(!t);
	}

	// method buat nomor jual otomatis
	private void nomor_jual() {
		try {
			stm = Con.createStatement();
			ResultSet rs = stm.executeQuery("select no_jual from jual");
			int brs = 0;

			while (rs.next()) {
				brs = rs.getRow();
			}
			if (brs == 0)
				txtNoJual.setText("1");
			else {
				int nom = brs + 1;
				txtNoJual.setText(Integer.toString(nom));
			}
			rs.close();
		} catch (SQLException e) {
			System.out.println("Error : " + e);
		}
	}

	// method simpan detail jual di tabel (temporary)
	private void simpan_ditabel() {
		try {
			String tKode = cmbKd_Brg.getSelectedItem().toString();
			String tNama = txtNm_Brg.getText();
			double hrg = Double.parseDouble(txtHarga.getText());
			int jml = Integer.parseInt(txtJml.getText());
			double tot = Double.parseDouble(txtTot.getText());
			tableModel.addRow(new Object[] { tKode, tNama, hrg, jml, tot });
			inisialisasi_tabel();
		} catch (Exception e) {
			System.out.println("Error : " + e);
		}
	}

	// method simpan transaksi penjualan pada table di MySql
	private void simpan_transaksi() {
		try {
			String xnojual = txtNoJual.getText();
			String xnmkons = txtNama.getText();
			format_tanggal();
			String xkode = cmbKd_Kons.getSelectedItem().toString();
			String msql = "insert into jual values('" + xnojual + "','" + xkode + "','" + tanggal + "')";
			stm.executeUpdate(msql);
			for (int i = 0; i < tblJual.getRowCount(); i++) {
				String xkd = (String) tblJual.getValueAt(i, 0);
				String xnama = (String) tblJual.getValueAt(i, 1);
				double xhrg = (Double) tblJual.getValueAt(i, 2);
				int xjml = (Integer) tblJual.getValueAt(i, 3);
				double xtotal = (Double) tblJual.getValueAt(i, 4);
				String zsql = "insert into djual values('" + xnojual + "','" + xkd + "'," + xhrg + "," + xjml + ")";
				String psql = "insert into lappenjualan values('" + xnojual + "','" + tanggal + "','" + xnmkons + "','"
						+ xkd + "','" + xnama + "'," + xhrg + "," + xjml + ",'" + xtotal + "')";
				stm.executeUpdate(psql);
				stm.executeUpdate(zsql);
			}

			JOptionPane.showMessageDialog(null, "Data penjualan berhasil disimpan.");
		} catch (SQLException e) {
			System.out.println("Error : " + e);
		}
	}

	// method membuat format tanggal sesuai dengan MySQL
	private void format_tanggal() {
		String DATE_FORMAT = "yyyy-MM-dd";
		java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat(DATE_FORMAT);
		Calendar c1 = Calendar.getInstance();
		int year = c1.get(Calendar.YEAR);
		int month = c1.get(Calendar.MONTH) + 1;
		int day = c1.get(Calendar.DAY_OF_MONTH);
		tanggal = Integer.toString(year) + "-" + Integer.toString(month) + "-" + Integer.toString(day);
	}

	private class PrintingTask extends SwingWorker<Object, Object> {
		private final MessageFormat headerFormat;
		private final MessageFormat footerFormat;
		private final boolean interactive;
		private volatile boolean complete = false;
		private volatile String message;

		public PrintingTask(MessageFormat header, MessageFormat footer, boolean interactive) {
			this.headerFormat = header;
			this.footerFormat = footer;
			this.interactive = interactive;
		}

		@Override
		protected Object doInBackground() {
			try {
				complete = text.print(headerFormat, footerFormat, true, null, null, interactive);
				message = "Printing " + (complete ? "complete" : "canceled");
			} catch (PrinterException ex) {
				message = "Sorry, a printer error occurred";
			} catch (SecurityException ex) {
				message = "Sorry, cannot access the printer due to security reasons";
			}
			return null;
		}

		@Override
		protected void done() {
			showMessage(!complete, message);
		}
	}

	private void showMessage(boolean isError, String message) {
		if (isError) {
			JOptionPane.showMessageDialog(null, message, "Error", JOptionPane.ERROR_MESSAGE);
		} else {
			JOptionPane.showMessageDialog(null, message, "Information", JOptionPane.INFORMATION_MESSAGE);
		}
	}

	public void itemTerpilih() {
		frmSelectBarang fDB = new frmSelectBarang();
		fDB.fAB = this;
		txtId.setText(idBrg);
		cmbKd_Brg.setSelectedItem(idBrg);
		txtNm_Brg.setText(namaBrg);
		txtHarga.setText(hargaBrg);
	}

	// Menghitung Kembalian
	private void hitung_bayar() {
		double xtotal, xbayar, xkembali;

		xtotal = Double.parseDouble(txtTotal.getText());
		xbayar = Double.parseDouble(txtBayar.getText());
		xkembali = xbayar - xtotal;
		String xkembalixx = Double.toString(xkembali);
		txtKembali.setText(xkembalixx);
	}

	// kosongi table penjualan
	private void kosong_table() {
		DefaultTableModel model = (DefaultTableModel) tblJual.getModel();
		model.setRowCount(0); // Menghapus semua baris dalam tabel
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPilih;
    private javax.swing.JComboBox<String> cmbKd_Brg;
    private javax.swing.JComboBox<String> cmbKd_Kons;
    private javax.swing.JButton cmdBatal;
    private javax.swing.JButton cmdCetak;
    private javax.swing.JButton cmdHapusItem;
    private javax.swing.JButton cmdKeluar;
    private javax.swing.JButton cmdSimpan;
    private javax.swing.JButton cmdTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblJual;
    private javax.swing.JTextArea text;
    private javax.swing.JTextField txtBayar;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtJml;
    private javax.swing.JTextField txtKembali;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNm_Brg;
    private javax.swing.JTextField txtNoJual;
    private javax.swing.JSpinner txtTgl;
    private javax.swing.JTextField txtTot;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
